//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nanva.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDeails = new HashSet<OrderDeails>();
            this.ProductFauther = new HashSet<ProductFauther>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> FeutherId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CommentId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Comment Comment { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDeails> OrderDeails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductFauther> ProductFauther { get; set; }
    }
}
