//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nanva.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFauther
    {
        public int Id { get; set; }
        public Nullable<int> Fuether { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Feuther Feuther { get; set; }
        public virtual Product Product { get; set; }
    }
}
